name: Plantopia Infrastructure/Terrafrom CI/CD Pipeline

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    terraform-plan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configure AWS Credentials via OIDC
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: eu-central-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.11.4"

        - name: Terraform Format Check
          run: terraform fmt -check

        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan -out=tfplan

        - name: Upload Terraform Plan artifact
          uses: actions/upload-artifact@v4
          with:
            name: tfplan
            path: tfplan

    terraform-apply:
      needs: terraform-plan
      runs-on: ubuntu-latest
      environment:
        name: production

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.sha }}

        - name: Download Terraform Plan artifact
          uses: actions/download-artifact@v4
          with:
            name: tfplan
            path: .

        - name: Configure AWS Credentials via OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: eu-central-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.11.4"

        - name: Terraform Init
          run: terraform init -lockfile=readonly

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan